Le nom des packages doivent utiliser les soulignés et pas des tirets.
domo-quebec/domo-quebec pull request #19
Opened 2024-01-27 17:22 UTC by MichelJourdain

2024-01-27 18:34 UTC, mdallaire commented on hydro-quebec/home-assistant/packages/hydro_quebec_production.yaml
La structure pour être compatible en mode package doit demeuré la même.

2024-01-27 19:25 UTC, MichelJourdain commented on hydro-quebec/home-assistant/packages/hydro_quebec_production.yaml
Je n’ai pas changé la structure, j’ai renommé les fichiers yaml pour utiliser des soulignés au lien de tirets. Si on utilise les noms que vous avez défini, ça donne une erreur.

![IMG_8470](https://github.com/domo-quebec/domo-quebec/assets/83040228/12a935fc-24af-47cd-8302-d2517951f90a)

2024-01-29 13:19 UTC, mdallaire requested changes

2024-01-29 13:19 UTC, mdallaire commented on hydro-quebec/home-assistant/packages/hydro_quebec_production.yaml
>      sensor:
@MichelJourdain Ici le fichier a été changé. Il faudrai simplement remettre le sensor à son format original, je vais pouvoir faire le merge avec les renommage après.

2024-01-30 19:35 UTC, mdallaire approved these changes

2024-01-30 19:36 UTC, merged